"""empty message

Revision ID: 3252f77996e5
Revises: 7b71e29c35d9
Create Date: 2020-03-30 14:41:30.832813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3252f77996e5'
down_revision = '7b71e29c35d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('version', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'version')
    # ### end Alembic commands ###
