"""empty message

Revision ID: 45c9d6881e27
Revises: 
Create Date: 2020-03-28 19:03:57.479258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c9d6881e27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('order_number', sa.String(length=25), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_license_license_key'), 'license', ['license_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_license_key'), table_name='license')
    op.drop_table('license')
    # ### end Alembic commands ###
