"""empty message

Revision ID: 63f88ca4de24
Revises: 0d639580a051
Create Date: 2020-03-29 12:22:47.129529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f88ca4de24'
down_revision = '0d639580a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license', sa.Column('edition', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license', 'edition')
    # ### end Alembic commands ###
