"""empty message

Revision ID: 9b693f8eb50d
Revises: 3252f77996e5
Create Date: 2020-04-02 15:21:43.370604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b693f8eb50d'
down_revision = '3252f77996e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('markdown', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'markdown')
    # ### end Alembic commands ###
